### ISSUE TITLE
Update nodejs

### ISSUE THREAD

**Issue by kassane** [korandoru/setup-zig#193]
```bash
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: korandoru/setup-zig@v1. 
```
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

cc: @tisonkun

**Comment by tisonkun** [comment]
Thanks for raising this issue. We resolve it months ago at https://github.com/korandoru/setup-zig/pull/166. But I forget to update `v1` tag. Now it should be resolved.
